### ISSUE TITLE
Request: `~for/foldr` 

### ISSUE THREAD

**Issue by jasonhemann** [stchang/generic-bind#20]
Given the other ones, I was surprised that `~for/foldr` isn't implemented. I'd like that, if you have the time.

**Comment by AlexKnauth** [comment]
When this package was implemented `for/foldr` didn't exist yet, but I can certainly look into adding it

**Comment by AlexKnauth** [comment]
The current `~for/common` seems to assume a `foldl`-like flow... it'll take work to either clean that up or re-implement some things for a `foldr` version.

Other maintenance such as adding the `#:result result-expr` clause to `~for/fold` will be comparatively easy, so I'll do that first

**Comment by stchang** [comment]
Somehow I missed that `for/foldr` got added in 7.4!

**Comment by AlexKnauth** [comment]
If the `#:do` binding clauses are implemented into a future version Racket, I could see it being much easier to implement `~for/foldr` in terms of that. It would be nice to just be able to delegate to Racket's `for/foldr` with `#:do` instead of starting from scratch on the implementation.

**Comment by AlexKnauth** [comment]
These `#:do` binding clauses: https://github.com/racket/racket/commit/d651c178fdd38026295970ee6b38002325af0ff4

**Comment by AlexKnauth** [comment]
I've started a PR to add `~for/foldr` and `~for*/foldr` here: #25
