### ISSUE TITLE
`~struct/contract` ? 

### ISSUE THREAD

**Issue by jasonhemann** [stchang/generic-bind#22]
I like `~struct`, I like `struct/contract`, and it's a shame to have to choose.

**Comment by AlexKnauth** [comment]
Since `(~struct foo (a b c))` is equivalent to `(struct foo (a b c))` and `(define-match-bind (foo a b c))`, you should be able to use `struct/contract` and `define-match-bind` together in the same way.

To define a `~struct/contract` would probably just be defining a macro that did that for you.

**Comment by AlexKnauth** [comment]
I've started a PR here:
https://github.com/stchang/generic-bind/pull/24

**Comment by AlexKnauth** [comment]
Documentation for the new `~struct/contract` macro here: https://docs.racket-lang.org/generic-bind/index.html#%28form._%28%28lib._generic-bind%2Fmain..rkt%29._~7estruct%2Fcontract%29%29
